### ISSUE TITLE
got this error when try to run test.py

### ISSUE THREAD

**Issue by faziii0** [nikhilroxtomar/TransResUNet#2]
(trans) bvb@BVB:~/Pictures/TransResUNet$ python test.py 
  0%|                                                   | 0/120 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/bvb/Pictures/TransResUNet/test.py", line 130, in <module>
    evaluate(model, save_path, test_x, test_y, size)
  File "/home/bvb/Pictures/TransResUNet/test.py", line 82, in evaluate
    cv2.imread(unet_mask[i], cv2.IMREAD_COLOR), line,
IndexError: list index out of range

**Comment by ztgzttt** [comment]
> (trans) bvb@BVB:~/Pictures/TransResUNet$ python test.py 0%| | 0/120 [00:01<?, ?it/s] Traceback (most recent call last): File "/home/bvb/Pictures/TransResUNet/test.py", line 130, in evaluate(model, save_path, test_x, test_y, size) File "/home/bvb/Pictures/TransResUNet/test.py", line 82, in evaluate cv2.imread(unet_mask[i], cv2.IMREAD_COLOR), line, IndexError: list index out of range



> (trans) bvb@BVB:~/Pictures/TransResUNet$ python test.py 0%| | 0/120 [00:01<?, ?it/s] Traceback (most recent call last): File "/home/bvb/Pictures/TransResUNet/test.py", line 130, in evaluate(model, save_path, test_x, test_y, size) File "/home/bvb/Pictures/TransResUNet/test.py", line 82, in evaluate cv2.imread(unet_mask[i], cv2.IMREAD_COLOR), line, IndexError: list index out of range

请问你解决这个问题了吗？
